import React, { useState, useCallback } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
  Share,
  Dimensions,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LineChart, BarChart } from 'react-native-chart-kit';
import { useFocusEffect } from '@react-navigation/native';
import { getLogs } from '../services/storageService';
import { getProfile as getProfileFromService } from '../services/profileService';
import { calculateWeeklyRisk } from '../services/riskEngine';
import { generateAnemiaReport } from '../services/geminiService';
import { supabase } from '../services/supabase';
import { globalStyles } from '../constants/styles';
import { useTheme } from '../contexts/ThemeContext';

const screenWidth = Dimensions.get('window').width - 32;

export default function ReportsScreen() {
  const { theme: colors } = useTheme();
  const styles = createStyles(colors);

  const chartConfig = {
    backgroundColor: colors.card,
    backgroundGradientFrom: colors.card,
    backgroundGradientTo: colors.card,
    decimalPlaces: 0,
    color: (opacity = 1) => `rgba(192, 57, 43, ${opacity})`,
    labelColor: () => colors.textSecondary,
    style: { borderRadius: 16 },
    propsForDots: { r: '4' },
  };

  const [logs, setLogs] = useState([]);
  const [logCount, setLogCount] = useState(0);
  const [weeklyRisk, setWeeklyRisk] = useState(null);
  const [aiReport, setAiReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [aiError, setAiError] = useState('');
  const [profile, setProfile] = useState(null);

  const loadLogs = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      const initialLogs = await getLogs(user.id, 7);
      const initialProfile = await getProfileFromService(user.id);

      setLogs(initialLogs);
      setProfile(initialProfile);

      const validLogs = initialLogs.map((entry) => entry.log).filter(Boolean);
      setLogCount(validLogs.length);
      setWeeklyRisk(
        validLogs.length >= 7
          ? calculateWeeklyRisk(validLogs, initialProfile)
          : null
      );

      Promise.all([
        getProfileFromService(user.id, (freshProfile) => {
          setProfile(freshProfile);
        }),
        getLogs(user.id, 7, (freshLogs) => {
          setLogs(freshLogs);
          const freshValidLogs = freshLogs.map((entry) => entry.log).filter(Boolean);
          setLogCount(freshValidLogs.length);
          if (freshValidLogs.length >= 7 && initialProfile) {
            setWeeklyRisk(calculateWeeklyRisk(freshValidLogs, initialProfile));
          }
        }),
      ]).catch((err) => {
        console.warn('Background refresh failed:', err?.message);
      });
    } catch (err) {
      console.error('Error loading logs:', err);
    }
  };

  useFocusEffect(useCallback(() => { loadLogs(); }, []));

  const labels = logs.map((d) => {
    const parts = d.date.split('-');
    return `${parts[2]}/${parts[1]}`;
  });

  const fatigueData    = logs.map((d) => d.log?.fatigue ?? 0);
  const energyData     = logs.map((d) => d.log?.energy ?? 0);
  const ironRichData   = logs.map((d) => d.log?.foods?.ironRich?.length ?? 0);
  const ironBlockData  = logs.map((d) => d.log?.foods?.ironBlocking?.length ?? 0);
  const vitaminCData   = logs.map((d) => d.log?.foods?.vitaminC?.length ?? 0);
  const junkData       = logs.map((d) => d.log?.foods?.junk?.length ?? 0);

  const getRiskColor = (log) => {
    if (!log) return colors.grey;
    const score = log.riskScore ?? 0;
    if (score <= 15) return colors.success;
    if (score <= 30) return colors.warning;
    return colors.primary;
  };

  const handleGenerateReport = async () => {
    setAiError('');
    setAiReport(null);
    const loggedCount = logs.filter((d) => d.log).length;
    if (loggedCount < 3) {
      setAiError('Log at least 3 days to generate a report');
      return;
    }
    setLoading(true);
    try {
      const report = await generateAnemiaReport(logs, profile);
      setAiReport(report);
    } catch (e) {
      setAiError(e.message || 'AI service unavailable, try again later');
    }
    setLoading(false);
  };

  const handleShare = async () => {
    const lines = logs.map((d) => {
      if (!d.log) return `${d.date}: Not logged`;
      return `${d.date}: Fatigue ${d.log.fatigue}, Energy ${d.log.energy}, Risk ${d.log.riskScore ?? 'N/A'}`;
    });
    const summary = `BloomCare: 7 Day Health Summary\n\n${lines.join('\n')}\n\nGenerated by BloomCare app`;
    await Share.share({ message: summary });
  };

  return (
    <ScrollView
      style={[globalStyles.container, { backgroundColor: colors.background }]}
      contentContainerStyle={globalStyles.scrollContent}
    >
      <Text style={globalStyles.heading}>Reports 📊</Text>

      {/* ── Risk Score Card ── */}
      <View style={styles.topRiskCard}>
        <Text style={styles.topRiskTitle}>Your Risk Score</Text>
        {logCount < 7 ? (
          <View style={styles.lockedWrap}>
            <Ionicons name="lock-closed-outline" size={28} color={colors.textSecondary} />
            <Text style={styles.lockedText}>
              Log {7 - logCount} more days to unlock your risk score
            </Text>
          </View>
        ) : (
          <>
            <Text style={styles.bigScore}>{weeklyRisk?.score ?? 0}/100</Text>
            <View style={[styles.levelPill, { backgroundColor: weeklyRisk?.color || colors.success }]}>
              <Text style={styles.levelPillText}>{weeklyRisk?.level || 'Low'}</Text>
            </View>
            <Text style={styles.topRiskSubtext}>Calculated from your last 7 days</Text>
            <Text style={styles.daysText}>{weeklyRisk?.daysLogged ?? 0}/7 days logged this week</Text>
          </>
        )}
      </View>

      {/* ── Charts ── */}
      <Text style={styles.sectionTitle}>This Week</Text>
      {logs.some((d) => d.log) ? (
        <>
          <Text style={styles.chartLabel}>Fatigue & Energy (7 days)</Text>
          <LineChart
            data={{
              labels,
              datasets: [
                { data: fatigueData.length ? fatigueData : [0], color: () => colors.danger, strokeWidth: 2 },
                { data: energyData.length ? energyData : [0], color: () => colors.success, strokeWidth: 2 },
              ],
              legend: ['Fatigue', 'Energy'],
            }}
            width={screenWidth}
            height={200}
            chartConfig={chartConfig}
            bezier
            style={styles.chart}
          />

          <Text style={styles.chartLabel}>Iron-rich foods per day</Text>
          <BarChart
            data={{
              labels,
              datasets: [{ data: ironRichData.length ? ironRichData : [0] }],
            }}
            width={screenWidth}
            height={180}
            chartConfig={{
              ...chartConfig,
              color: (opacity = 1) => `rgba(39, 174, 96, ${opacity})`,
            }}
            style={styles.chart}
            yAxisLabel=""
            yAxisSuffix=""
            fromZero
            showValuesOnTopOfBars
          />

          <Text style={styles.chartLabel}>Vitamin C foods per day</Text>
          <BarChart
            data={{
              labels,
              datasets: [{ data: vitaminCData.length ? vitaminCData : [0] }],
            }}
            width={screenWidth}
            height={180}
            chartConfig={{
              ...chartConfig,
              color: (opacity = 1) => `rgba(243, 156, 18, ${opacity})`,
            }}
            style={styles.chart}
            yAxisLabel=""
            yAxisSuffix=""
            fromZero
            showValuesOnTopOfBars
          />

          <Text style={styles.chartLabel}>Iron-blocking foods per day</Text>
          <BarChart
            data={{
              labels,
              datasets: [{ data: ironBlockData.length ? ironBlockData : [0] }],
            }}
            width={screenWidth}
            height={180}
            chartConfig={{
              ...chartConfig,
              color: (opacity = 1) => `rgba(231, 76, 60, ${opacity})`,
            }}
            style={styles.chart}
            yAxisLabel=""
            yAxisSuffix=""
            fromZero
            showValuesOnTopOfBars
          />

          <Text style={styles.chartLabel}>Junk & fried foods per day</Text>
          <BarChart
            data={{
              labels,
              datasets: [{ data: junkData.length ? junkData : [0] }],
            }}
            width={screenWidth}
            height={180}
            chartConfig={{
              ...chartConfig,
              color: (opacity = 1) => `rgba(192, 57, 43, ${opacity})`,
            }}
            style={styles.chart}
            yAxisLabel=""
            yAxisSuffix=""
            fromZero
            showValuesOnTopOfBars
          />
        </>
      ) : (
        <Text style={globalStyles.bodyText}>No logs yet this week. Start tracking!</Text>
      )}

      {/* ── Risk Trend ── */}
      <Text style={styles.sectionTitle}>Risk Trend</Text>
      <View style={styles.trendRow}>
        {logs.map((d) => (
          <View key={d.date} style={styles.trendItem}>
            <View
              style={[
                styles.trendDot,
                { backgroundColor: d.log ? getRiskColor(d.log) : colors.grey },
              ]}
            />
            <Text style={styles.trendDate}>{d.date.slice(5)}</Text>
            <Text style={styles.trendLabel}>
              {d.log ? d.log.riskLevel?.slice(0, 3) : '-'}
            </Text>
          </View>
        ))}
      </View>

      {/* ── AI Report ── */}
      <Text style={styles.sectionTitle}>AI Report</Text>
      <TouchableOpacity
        style={[globalStyles.primaryButton, { backgroundColor: colors.primary }]}
        onPress={handleGenerateReport}
        disabled={loading}
      >
        <Text style={globalStyles.primaryButtonText}>
          {loading ? 'Generating...' : '✨ Generate AI Report'}
        </Text>
      </TouchableOpacity>

      {loading && (
        <ActivityIndicator
          size="large"
          color={colors.primary}
          style={{ marginTop: 16 }}
        />
      )}

      {aiError ? <Text style={globalStyles.errorText}>{aiError}</Text> : null}

      {aiReport && (
        <View style={[globalStyles.card, { marginTop: 12 }]}>
          <Text style={styles.reportSection}>Overall Risk Assessment</Text>
          <Text style={[styles.riskBadge, {
            color: aiReport.riskLevel === 'Low'
              ? colors.success
              : aiReport.riskLevel === 'High'
                ? colors.danger
                : colors.warning,
          }]}>
            {aiReport.riskLevel}
          </Text>

          <Text style={styles.reportSection}>Key Observations</Text>
          {aiReport.observations.map((o, i) => (
            <Text key={i} style={styles.bullet}>• {o}</Text>
          ))}

          <Text style={styles.reportSection}>Diet Recommendations</Text>
          {aiReport.dietRecommendations.map((d, i) => (
            <Text key={i} style={styles.bullet}>• {d}</Text>
          ))}

          <Text style={styles.reportSection}>Lifestyle Tip</Text>
          <Text style={globalStyles.bodyText}>{aiReport.lifestyleTip}</Text>

          <Text style={styles.disclaimer}>{aiReport.disclaimer}</Text>
        </View>
      )}

      {/* ── Export ── */}
      <Text style={styles.sectionTitle}>Export</Text>
      <TouchableOpacity style={globalStyles.secondaryButton} onPress={handleShare}>
        <Text style={globalStyles.secondaryButtonText}>📤 Share Summary</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const createStyles = (colors) => StyleSheet.create({
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primary,
    marginTop: 16,
    marginBottom: 10,
  },
  chartLabel: {
    fontSize: 13,
    color: colors.textSecondary,
    marginBottom: 6,
  },
  chart: {
    borderRadius: 16,
    marginBottom: 16,
  },
  trendRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  trendItem: { alignItems: 'center', flex: 1 },
  trendDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    marginBottom: 4,
  },
  trendDate: { fontSize: 9, color: colors.textSecondary },
  trendLabel: { fontSize: 9, color: colors.textPrimary, fontWeight: '600' },
  reportSection: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
    marginTop: 10,
    marginBottom: 6,
  },
  riskBadge: { fontSize: 22, fontWeight: '800', marginBottom: 8 },
  bullet: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 20,
    marginBottom: 4,
  },
  disclaimer: {
    fontSize: 11,
    color: colors.textSecondary,
    fontStyle: 'italic',
    marginTop: 12,
    lineHeight: 16,
  },
  topRiskCard: {
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 18,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  topRiskTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 10,
  },
  lockedWrap: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  lockedText: {
    marginLeft: 10,
    flex: 1,
    fontSize: 14,
    color: colors.textSecondary,
  },
  bigScore: {
    fontSize: 48,
    fontWeight: '800',
    color: colors.textPrimary,
    lineHeight: 56,
  },
  levelPill: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginTop: 6,
  },
  levelPillText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.white,
  },
  topRiskSubtext: {
    marginTop: 10,
    fontSize: 13,
    color: colors.textSecondary,
  },
  daysText: {
    marginTop: 6,
    fontSize: 12,
    color: colors.textSecondary,
  },
});